### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by minzastro** [andresgsaravia/research-engine#223]
Is it possible to print things out in a nice way? For example, to print the whole notebook with or without comments?

**Comment by andresgsaravia** [comment]
I have a view for the *writings* which shows only the content of the article. For example, [this artcile](https://research-engine.appspot.com/37001/writings/1) is rendered [as this](https://research-engine.appspot.com/37001/writings/1/_html) which might be decent enough for printing. Is something like this helpful?. I could make something similar for the notebooks and other stuff.

**Comment by minzastro** [comment]
Yes, this will help.
By the way, exporting writing to HTML breaks when writing has no text at all.

**Comment by minzastro** [comment]
Hey, this looks cool now!

**Comment by minzastro** [comment]
Note: Tables CSS does not seem to work properly on printing

**Comment by andresgsaravia** [comment]
The CSS is now working for tables, though they take the whole page and might look weird if you have a small number of columns...
